### ISSUE TITLE
Handle Config File

### ISSUE THREAD

**Issue by Adobe-Android** [glenvollmer/nap#1]
Check if config file exists
If one exists, read from it
If one doesn't exist, generate one and populate it with the path given by the user

- [x] Create read from config file logic

- [x] Handle the case if a config file doesn't yet exist

- [x] Get a path from the user for use when generating a config file

**Comment by glenvollmer** [comment]
hey man! you should make this a ticket on the project board that way we can track our dev progress in a consolidated place. we should reserve this issue board for bugs and issues with the code as it is on the master branch once we get some stuff going.

**Comment by glenvollmer** [comment]
https://github.com/glenvollmer/nap/projects/1

**Comment by Adobe-Android** [comment]
#11
